### ISSUE TITLE
Баг при перемещении в библиотеку разума.

### ISSUE THREAD

**Issue by Viptunbeqwfwew** [MoonlitJolteon/hex-keys-addon#12]
Сборка:
lanishextendedstaves-forge-1.19.2-0.2.0.jar
mediaworks-forge-1.19.2-1.0.7.jar
moreiotas-forge-1.19.2-0.0.4.jar
Patchouli-1.19.2-76.jar.disenabled
Patchouli-1.19.2-77.jar
paucal-forge-1.19.2-0.5.0.jar
u_team_core-forge-1.19.2-4.4.3.297.jar
useful_backpacks-1.19.2-1.14.1.107.jar
wnboi-0.0.4-forge.jar
amethysttoolsmod-1.19-1.6.2.jar
architectury-6.5.85-forge.jar
curios-forge-1.19.2-5.1.6.3.jar
geckolib-forge-1.19-3.1.40.jar
hexal-forge-1.19.2-0.2.19.jar
hexcasting-forge-1.19.2-0.10.3.jar
HexCircus-1.1.1.jar
hexgloop-1.19.2-0.2.0-forge.jar
hexkeys-forge-1.19.2-0.1.2.jar
hexresearch-forge-1.19.2-1.0.1.jar
intarsia-1.1.6-beta.jar
jei-1.19.2-forge-11.6.0.1020.jar
journeymap-1.19.2-5.9.7-forge.jar
kotlinforforge-3.12.0-all.jar

Описание:
При первом перемещении всё работала в штатном режиме. Но в какой-то момент я погиб. И тогда перемещение в библеотеку стало не возможна. Меня забрасывает в пустоту за миллионы блоков до библиотеки.

Я решил уточнить не конфликт ли это. И запустил только аддон и его зависимости, но ситуация повторилась.

Далее решил посмотреть исходный код. Оказалось, что после смерти проподает MINDSCAPE_VERSION_NUM из NBT тега игрока, поэтому функция getMindscapePos выдавала неверные координаты для перемещения.

Просьба пофиксить это.

**Comment by MoonlitJolteon** [comment]
Unfortunately I can't easily help you if can't understand you. I only speak English and I don't trust giigle translate or similar to successfully translate

**Comment by Viptunbeqwfwew** [comment]
I bad know English. But try now translated.

**Comment by Viptunbeqwfwew** [comment]
Collections:
lanishextendedstaves-forge-1.19.2-0.2.0.jar
mediaworks-forge-1.19.2-1.0.7.jar
moreiotas-forge-1.19.2-0.0.4.jar
Patchouli-1.19.2-76.jar.disenabled
Patchouli-1.19.2-77.jar
paucal-forge-1.19.2-0.5.0.jar
u_team_core-forge-1.19.2-4.4.3.297.jar
useful_backpacks-1.19.2-1.14.1.107.jar
wnboi-0.0.4-forge.jar
amethysttoolsmod-1.19-1.6.2.jar
architectury-6.5.85-forge.jar
curios-forge-1.19.2-5.1.6.3.jar
geckolib-forge-1.19-3.1.40.jar
hexal-forge-1.19.2-0.2.19.jar
hexcasting-forge-1.19.2-0.10.3.jar
HexCircus-1.1.1.jar
hexgloop-1.19.2-0.2.0-forge.jar
hexkeys-forge-1.19.2-0.1.2.jar
hexresearch-forge-1.19.2-1.0.1.jar
intarsia-1.1.6-beta.jar
jei-1.19.2-forge-11.6.0.1020.jar
journeymap-1.19.2-5.9.7-forge.jar
kotlinforforge-3.12.0-all.jar

Discription:
Firsted transposition on mindscape library, all work OK. But in moment I dies. Afte I cast rune key my space, but my teleported to million blocks from my library. I repiet a lot, but result not chancged.

I see, you source code. After death, reset NBT HexKeys from player (not recovery). MINDSCAPE_VERSION_NUM do not must miss.

**Comment by Viptunbeqwfwew** [comment]
<img width="625" alt="(1)" src="https://github.com/user-attachments/assets/60800ac6-ecc9-4b0a-b610-e0125df4975a">
<img width="631" alt="(0)" src="https://github.com/user-attachments/assets/6ceca7c3-552b-48ee-a8ec-0d5b5669865d">

**Comment by Viptunbeqwfwew** [comment]
<img width="653" alt="(2)" src="https://github.com/user-attachments/assets/5bea663e-0213-4ba7-bc98-6862e7018c3a">
This afte first move, afte death. Above screenshots this exactly afte death.

**Comment by Viptunbeqwfwew** [comment]
https://github.com/user-attachments/assets/b8ef6380-eb1d-406c-a182-a8c53fb9684d

@MoonlitJolteon, watch the video.

**Comment by MoonlitJolteon** [comment]
Should be fixed by #13
