### ISSUE TITLE
library flight outside of the mindscape

### ISSUE THREAD

**Issue by ChloeTax** [MoonlitJolteon/hex-keys-addon#14]
if you're flying when you leave the mindscape, you'll still be able to fly until you land

**Comment by furry-stuff** [comment]
This should be fixed with the most recent push, just haven't had the chance to test and verify before uploading to modrinth and curseforge. Was previously reported in issue #5

**Comment by MoonlitJolteon** [comment]
This was previously reported and subsequently fixed in issue #5 and PR #13. Just awaiting some more testing before I push an update
