### ISSUE TITLE
Are there possible conflicting mods?

### ISSUE THREAD

**Issue by WaterWaterovich** [MoonlitJolteon/hex-keys-addon#6]
Hello, I'm having a problem using the Library Key spell. When casting it, the game tries to load the world, but eventually crashes. Does the addon have conflicts with optimization mods or a conflict when using quilt?

**Comment by MoonlitJolteon** [comment]
I'm not aware of any conflicts, though I can't say for quilt as quilt is untested from my side. I have had a few reports of the mindscape crashing games while loading so it's a good chance I'm just doing it in an inefficient method. I've been extremely busy with some personal life stuff so I've been unable to work on the mod for the past month or so, but I'll mark this on my list as one of the first things to look into when I get back to it.

**Comment by WaterWaterovich** [comment]
Hello, sorry for the late reply, I finally switched to fabriс and the spell worked without crashing. I'm not entirely sure that the problem is in quilt, because I also removed a lot of mods, but still after the transition the spell works
